{
	"version": 1594734892,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/bloco-sheet0.png",
		"images/fundo-sheet0.png",
		"images/particles.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/background-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"media/y2mate.com - bubble_popping_sound_effect_royalty_free_wjaos-s-cgu (mp3cut.net).m4a",
		"media/y2mate.com - bubble_popping_sound_effect_royalty_free_wjaos-s-cgu (mp3cut.net).ogg",
		"media/y2mate.com - victory_sound_effect_hd_1zsieporcos_64kbps (mp3cut.net).m4a",
		"media/y2mate.com - victory_sound_effect_hd_1zsieporcos_64kbps (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}